[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "skrom"
version = "1.0.0"
description = "A python toolbox for projection-based ROMs"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }

authors = [
  { name = "Ali Syed", email = "saabidi1@tamu.edu" },
  { name = "Suparno Bhattacharyya", email = "suparno@iitisc.ac.in" }
]

dependencies = [
  "numpy",
  "scipy",
  "sympy",
  "matplotlib==3.8.4",
  "scikit-fem[all]",
  "pyamg",
  "pyDOE",
  "ptitprince",
  "scikit-learn",
  "h5py",
  "gmsh",

  # Install local style package automatically
  "sci_mplstyle_package @ file:./src/skrom/utils/visualization/sci_mplstyle_package"
]

# NOTE: The petsc4py wheels used by the `petsc311` extra are sourced from the simnibs/petsc4py project:
# https://github.com/simnibs/petsc4py

[project.optional-dependencies]
petsc311 = [
  # Windows (x86_64)
  "petsc4py @ file:./petsc_installer/petsc4py-3.23.2-cp311-cp311-win_amd64.whl ; python_version == '3.11' and sys_platform == 'win32' and platform_machine == 'AMD64'",
  "mpi4py ; sys_platform == 'win32'",

  # Linux (x86_64)
  "petsc4py @ file:./petsc_installer/petsc4py-3.23.2-cp311-cp311-manylinux_2_28_x86_64.whl ; python_version == '3.11' and sys_platform == 'linux' and platform_machine == 'x86_64'",

  # macOS (Apple Silicon, macOS 14+ wheel tag)
  "petsc4py @ file:./petsc_installer/petsc4py-3.23.2-cp311-cp311-macosx_14_0_arm64.whl ; python_version == '3.11' and sys_platform == 'darwin' and platform_machine == 'arm64'",
]


[project.scripts]
skrom = "skrom.cli:cli"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.package-data]
skrom = [
  "templates/problem_template/*.py",
  "templates/problem_template/*.ipynb",
]

[tool.setuptools.exclude-package-data]
"*" = ["*.egg-info/*", "build/*", "__pycache__/*"]
